"""Module for the dlinear repository"""

module(
    name = "dlinear",
    version = "0.0.1",
)

# Apache License 2.0 | rules_cc for building C++ libraries with Bazel
bazel_dep(name = "rules_cc", version = "0.2.17")

# Apache License 2.0 | rules_foreign_cc for building C++ libraries with other build systems
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")

# Apache License 2.0 | rules_python for building python targets
bazel_dep(name = "rules_python", version = "1.9.0")

# Apache License 2.0 | bazel rules to gather system information
bazel_dep(name = "platforms", version = "1.0.0")

# https://github.com/madler/zlib/blob/develop/LICENSE | zlib compression library
bazel_dep(name = "zlib", version = "1.3.2")

# Apache License 2.0 | utility rules for Bazel
bazel_dep(name = "bazel_skylib", version = "1.9.0")

# https://github.com/pybind/pybind11_bazel/blob/master/LICENSE | pybind11 for binding C++ and Python
bazel_dep(name = "pybind11_bazel", version = "3.0.1")

# https://github.com/libarchive/bzip2/blob/master/COPYING | Compression library
bazel_dep(name = "bzip2", version = "1.0.8.bcr.4")

# MIT | argparse implementation for modern C++
bazel_dep(name = "argparse", version = "3.2.0")

# MIT | C++ library for formatting text
bazel_dep(name = "fmt", version = "11.0.2")

# BSD | lexical analyser generator
bazel_dep(name = "rules_flex", version = "0.4")

# https://www.gnu.org/software/bison/manual/html_node/Conditions.html | Bison parser generator
bazel_dep(name = "rules_bison", version = "0.4.bcr.1")

# Apache License 2.0 | Open Neural Network Exchange (ONNX) format support
bazel_dep(name = "onnx", version = "1.17.0")

# MIT | C++ json library
bazel_dep(name = "nlohmann_json", version = "3.12.0.bcr.1")

# Mozilla Public License 2.0 | C++ library that handles matrices and vectors
bazel_dep(name = "eigen", version = "5.0.1.bcr.1")

# MIT | logging library
bazel_dep(name = "spdlog", version = "1.17.0")

# BSD-3 | C++ library for multi-dimensional arrays
bazel_dep(name = "xtensor", version = "0.27.1")

# https://github.com/cpplint/cpplint/blob/develop/LICENSE | Google C++ Style Guide
bazel_dep(name = "cpplint", version = "2.0.2", dev_dependency = True)

# BSD-3-Clause license | c++ test suite by Google
bazel_dep(name = "googletest", version = "1.17.0.bcr.2", dev_dependency = True)

# Apache License 2.0 | Bazel rules for packaging the project
bazel_dep(name = "rules_pkg", version = "1.2.0", dev_dependency = True)

# Apache License 2.0 | Bazel rules for packaging the project
bazel_dep(name = "rules_doxygen", version = "2.6.2", dev_dependency = True)

# MIT | rules for dealing with target dependencies
bazel_dep(name = "depend_on_what_you_use", version = "0.14.0", dev_dependency = True)

# Apache License 2.0 | Integration of Boost into Bazel
bazel_dep(name = "boost.multiprecision", version = "1.90.0.bcr.1")
bazel_dep(name = "boost.serialization", version = "1.90.0.bcr.1")

# BSD-3-Clause license | C++ library of common algorithms and data structures
bazel_dep(name = "abseil-cpp", version = "20260107.1")

# BSD-3-Clause license | C++ library for serialization and deserialization of data
bazel_dep(name = "protobuf", version = "34.1")

# Repository dependencies

## Github repositories

github_archive = use_repo_rule("//tools:git_archive.bzl", "github_archive")

# Apache License 2.0 | linear programming solver
github_archive(
    name = "soplex",
    build_file = "//third_party:soplex.BUILD.bazel",
    commit = "91f8c2a8b92fd67d474c9195917f1ff527f05aca",
    repository = "TendTo/soplex",
    sha256 = "09cef69536bdb11af9d148c28a36289d7a7a196052c46fbfa7e049ca6b005d14",
)

# GNU General Public License v3.0 | delta-complete linear programming solver
github_archive(
    name = "qsopt_ex",
    build_file = "//third_party:qsopt_ex.BUILD.bazel",
    commit = "4646dc3bec76532827c479f7c51d8a71a35806de",
    repository = "TendTo/qsopt-ex",
    sha256 = "610222f0023213e17b395d23fdcaf918d6102b020e445902014e0518a30c900d",
)

# MIT | SAT solver
github_archive(
    name = "picosat",  # MIT
    build_file = "//third_party:picosat.BUILD.bazel",
    commit = "ee542566ca89717af1b4558b0b3f226eb3b6b42d",  # master
    repository = "dreal-deps/picosat",
    sha256 = "9a047b7ba3ac1075a2288d35045585e2e3c24961f078f30ad97a313b8e539eb2",
)

# MIT | cadical SAT solver
github_archive(
    name = "cadical",
    build_file = "//third_party:cadical.BUILD.bazel",
    commit = "rel-2.1.0",
    repository = "arminbiere/cadical",
    sha256 = "0652b2b3f2dbaf19f1940cd882823bce44b6fc7a3c025066da7932254bcee237",
)

## HTTP repositories

http_archive = use_repo_rule("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

# GNU Lesser General Public License v3.0 | arbitrary precision arithmetic library
http_archive(
    name = "gmp",
    build_file = "//third_party:gmp.BUILD.bazel",
    sha256 = "a3c2b80201b89e68616f4ad30bc66aee4927c3ce50e33929ca819d5c43538898",
    strip_prefix = "gmp-6.3.0",
    url = "https://ftp.gnu.org/gnu/gmp/gmp-6.3.0.tar.xz",
)

# MIT | c++ library for arbitrary precision arithmetic
http_archive(
    name = "mpfr",
    build_file = "//third_party:mpfr.BUILD.bazel",
    sha256 = "b67ba0383ef7e8a8563734e2e889ef5ec3c3b898a01d00fa0a6869ad81c6ce01",
    strip_prefix = "mpfr-4.2.2",
    url = "https://www.mpfr.org/mpfr-current/mpfr-4.2.2.tar.xz",
)

# Extensions

doxygen_extension = use_extension("@rules_doxygen//:extensions.bzl", "doxygen_extension")
doxygen_extension.configuration(
    platform = "linux",
    sha256 = "0ec2e5b2c3cd82b7106d19cb42d8466450730b8cb7a9e85af712be38bf4523a1",
    version = "1.15.0",
)
use_repo(doxygen_extension, "doxygen")

flex = use_extension("@rules_flex//flex/extensions:flex_repository_ext.bzl", "flex_repository_ext")
flex.repository(
    name = "flex",
    extra_copts = ["-O3"],
    version = "2.6.4",
)
use_repo(flex, "flex")

register_toolchains("@flex//:toolchain")

bison = use_extension("@rules_bison//bison/extensions:bison_repository_ext.bzl", "bison_repository_ext")
bison.repository(
    name = "bison",
    extra_copts = ["-O3"],
    version = "3.3.2",
)
use_repo(bison, "bison")

register_toolchains("@bison//:toolchain")

new_local_repository = use_repo_rule("//tools:local.bzl", "new_local_repository")

new_local_repository(
    name = "system_deps",
    build_file = "//third_party:system_deps.BUILD.bazel",
    path = "/usr",
)

PYTHON_VERSIONS = [
    "3.9",
    "3.10",
    "3.11",
    "3.12",
    "3.13",
    "3.14",
]

python = use_extension("@rules_python//python/extensions:python.bzl", "python")

[
    python.toolchain(python_version = v)
    for v in PYTHON_VERSIONS
]

use_repo(
    python,
    "python_3_10",
    "python_3_11",
    "python_3_12",
    "python_3_13",
    "python_3_14",
    "python_3_9",
    "python_versions",
)

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")

[
    pip.parse(
        hub_name = "pypi",
        python_version = v,
        requirements_lock = "//tools:requirements.txt",
    )
    for v in PYTHON_VERSIONS
]

use_repo(pip, "pypi")
