@startuml onnx
#WhiteSmoke:**Input**;
split 
#PowderBlue:Conv;
#Pink:ReLU;
#PowderBlue:Conv;
split again
#PowderBlue:Conv;
end split
#LightGray:Add;
#Pink:ReLU;
#Tan:Pad;
#Wheat:Flatten;
#WhiteSmoke:**Output**;
@enduml
